In [1]:
import pandas as pd
import numpy as np

trmean=pd.read_csv('/home/aaftab/Github/Flipr-Hackathon/Mean-Filled.csv')
tstdt=pd.read_csv('/home/aaftab/Github/Flipr-Hackathon/Mean-Filled-test.csv')

In [2]:
features=trmean.copy()
features.drop('Infect_Prob',axis=1,inplace=True)
results=trmean['Infect_Prob']
testfeatures=tstdt.copy()

from sklearn import preprocessing
standard= preprocessing.StandardScaler()

features = standard.fit_transform(features)
testfeatures=standard.fit_transform(testfeatures)

features=pd.DataFrame(features)
testfeatures=pd.DataFrame(testfeatures)

In [4]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import RFE

lmr = RandomForestRegressor(n_estimators = 100, random_state = 42)
lgr2= RandomForestRegressor(n_estimators = 100, random_state = 42)


modellr = lmr.fit(features,results)

rfe = RFE(lmr, 20)
rfe = rfe.fit(features,results)
print(rfe.support_)
print(rfe.ranking_)


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, results, test_size=0.3, random_state=0)
modelval=lgr2.fit(X_train,y_train)
y_pred = modelval.predict(X_test)
y_pred2=modelval.predict(X_train)

import math
from math import sqrt
from sklearn.metrics import mean_squared_error

mse1=mean_squared_error(y_train, y_pred2)
rmse1=sqrt(mse1)
print(str(rmse1)+' Training error')
mse2=mean_squared_error(y_test, y_pred)
rmse2=sqrt(mse1)
print(str(rmse2)+' Testing Error')

print ('score ' + str(modelval.score(X_train, y_train)))
print ('score '+str(modelval.score(X_test, y_test)))
        
predictions = modellr.predict(testfeatures)
pred=pd.DataFrame(predictions)
        
pred.to_csv('RandomForestPredictions.csv')

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
3.2652274728433657 Training error
3.2652274728433657 Testing Error
score 0.9048063909209298
score 0.3241489471086575


In [3]:
#dropping columns deemed unneccesary by recursive feature elimination
testfeatures.drop(testfeatures.columns[[18,19,20,21,22,23,25,26,27,28,29,30,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52]],axis=1,inplace=True)
features.drop(features.columns[[18,19,20,21,22,23,25,26,27,28,29,30,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52]],axis=1,inplace=True)

from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import RFE

lmr = RandomForestRegressor(n_estimators = 100, random_state = 42)
lgr2= RandomForestRegressor(n_estimators = 100, random_state = 42)

modellr = lmr.fit(features,results)
    
rfe = RFE(lmr, 20)
rfe = rfe.fit(features,results)
print(rfe.support_)
print(rfe.ranking_)


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, results, test_size=0.3, random_state=0)
modelval=lgr2.fit(X_train,y_train)
y_pred = modelval.predict(X_test)
y_pred2=modelval.predict(X_train)

import math
from math import sqrt
from sklearn.metrics import mean_squared_error

mse1=mean_squared_error(y_train, y_pred2)
rmse1=sqrt(mse1)
print(str(rmse1)+'Training error')
mse2=mean_squared_error(y_test, y_pred)
rmse2=sqrt(mse1)
print(str(rmse2)+'Testing Error')

print ('score ' + str(modelval.score(X_train, y_train)))
print ('score '+str(modelval.score(X_test, y_test)))
        
predictions = modellr.predict(testfeatures)
pred=pd.DataFrame(predictions)
        
pred.to_csv('RandomForestRegressionPredictions.csv')

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
3.2652274728433657Training error
3.2652274728433657Testing Error
score 0.9048063909209298
score 0.3241489471086575


In [8]:
#clearly it is overfitting
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

parameters = { 'max_features':np.arange(5,21),'n_estimators':[500],'min_samples_leaf': [10,50,100,200,500]}
lmreval = RandomForestRegressor()
random_grid = GridSearchCV(lmreval, parameters, cv = 5)
print(random_grid)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=RandomForestRegressor(bootstrap=True, criterion='mse',
                                             max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators='warn', n_jobs=None,
                                             oob_score=False, random_state=None,
                                             verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'max_features': array([ 5,  6, 

In [12]:


random_grid.fit(features, results)


AttributeError: 'GridSearchCV' object has no attribute 'best_params'

In [13]:

print(random_grid.best_params_)

{'max_features': 12, 'min_samples_leaf': 50, 'n_estimators': 500}


In [3]:
testfeatures.drop(testfeatures.columns[[18,19,20,21,22,23,25,26,27,28,29,30,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52]],axis=1,inplace=True)
features.drop(features.columns[[18,19,20,21,22,23,25,26,27,28,29,30,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52]],axis=1,inplace=True)

from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import RFE

lmr = RandomForestRegressor(n_estimators = 50, random_state = 42,max_features=12,min_samples_leaf=50)
lgr2= RandomForestRegressor(n_estimators = 50, random_state = 42,max_features=12,min_samples_leaf=50)

modellr = lmr.fit(features,results)
    
rfe = RFE(lmr, 20)
rfe = rfe.fit(features,results)
print(rfe.support_)
print(rfe.ranking_)


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, results, test_size=0.3, random_state=0)
modelval=lgr2.fit(X_train,y_train)
y_pred = modelval.predict(X_test)
y_pred2=modelval.predict(X_train)

import math
from math import sqrt
from sklearn.metrics import mean_squared_error

mse1=mean_squared_error(y_train, y_pred2)
rmse1=sqrt(mse1)
print(str(rmse1)+'Training error')
mse2=mean_squared_error(y_test, y_pred)
rmse2=sqrt(mse1)
print(str(rmse2)+'Testing Error')

print ('score ' + str(modelval.score(X_train, y_train)))
print ('score '+str(modelval.score(X_test, y_test)))
        
predictions = modellr.predict(testfeatures)
pred=pd.DataFrame(predictions)
        
pred.to_csv('RandomForestRegressionPredictions.csv')

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
8.227782465985133Training error
8.227782465985133Testing Error
score 0.3955693058547005
score 0.3369455314370078
